version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"

  - package-ecosystem: "npm"
    directory: "/packages/hardhat-zksync-deploy"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"

  - package-ecosystem: "npm"
    directory: "/packages/hardhat-zksync-solc"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"

  - package-ecosystem: "npm"
    directory: "/packages/hardhat-zksync-vyper"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
