version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/hardhat-zksync-deploy"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/hardhat-zksync-solc"
    schedule:
      interval: "daily"
