name: CI

on:
  push:

jobs:
  compilation:
    runs-on: ubuntu-latest
    name: Compilation tests
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Setup environment
        run: |
          yarn install

      - name: Test zksolc compiler plugin
        run: |
          cd packages/hardhat-zksync-solc
          yarn test

      - name: Test zkvyper compiler plugin
        run: |
          cd packages/hardhat-zksync-vyper
          yarn test

  deployment:
    runs-on: ubuntu-latest
    name: Deployment tests
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: matter-labs/local-setup
          path: local-setup

      - name: Run server
        run: |
          cd local-setup
          mkdir -p ./volumes/postgres ./volumes/geth ./volumes/zksync/env/dev ./volumes/zksync/data
          docker-compose pull
          docker-compose up &>../server.log &
          sleep 60

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Setup environment
        run: |
          yarn install
          yarn build

      - name: Test zksolc example
        run: |
          cd examples/basic-example
          yarn hardhat compile
          yarn hardhat deploy-zksync

      - name: Test zkvyper example
        run: |
          cd examples/vyper-example
          yarn hardhat compile
          yarn hardhat deploy-zksync

      - name: Show logs
        if: always()
        run: |
          cat server.log

