name: CI

on:
  push:

jobs:
  compilation:
    runs-on: ubuntu-latest
    name: Compilation tests
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Setup environment
        run: |
          yarn install

      - name: Test zksolc compiler plugin
        run: |
          cd packages/hardhat-zksync-solc
          yarn test

      - name: Test zkvyper compiler plugin
        run: |
          cd packages/hardhat-zksync-vyper
          yarn test

  deployment:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        # solc: [0.8.16, 0.7.6]

    runs-on: ${{ matrix.os }}

    name: Deployment tests
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: matter-labs/local-setup
          path: local-setup

      - name: Run server
        run: |
          cd local-setup
          ./start.sh &>../server.log &

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Setup environment
        run: |
          yarn install
          yarn build

      - name: Wait until server is up
        run: |
          while ! curl -s -X POST -d '{"jsonrpc":"2.0","method":"net_version","id":1}' -H 'Content-Type: application/json' 0.0.0.0:3050; do sleep 1; done

      - name: Test zksolc example
        run: |
          cd examples/basic-example
          yarn hardhat compile
          yarn hardhat deploy-zksync

      - name: Test zkvyper example
        run: |
          cd examples/vyper-example
          yarn hardhat compile
          yarn hardhat deploy-zksync

      - name: Show logs
        if: always()
        run: |
          cat server.log

