name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Compilation tests
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Setup environment
        run: |
          yarn install

      - name: Test zksolc compiler plugin
        run: |
          cd packages/hardhat-zksync-solc
          yarn test

      - name: Test zkvyper compiler plugin
        run: |
          cd packages/hardhat-zksync-vyper
          yarn test
